<Project>
  <PropertyGroup>
    <TargetFrameworks>net10.0;net10.0-windows</TargetFrameworks>
  </PropertyGroup>
  <Import Project="$(MSBuildThisFileDirectory)..\Directory.Build.props" />
  <ItemGroup>
    <PackageReference Include="Shouldly" Version="4.0.3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0" />
    <ProjectReference Include="..\..\UiPath.Workflow.Runtime\UiPath.Workflow.Runtime.csproj" />
  </ItemGroup>
</Project>