<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../UiPath.Workflow/UiPath.Workflow.csproj" />
    <ProjectReference Include="../JsonFileInstanceStore/JsonFileInstanceStore.csproj" />
    <ProjectReference Include="../TestObjects/TestObjects.csproj" />
  </ItemGroup>

</Project>
