<Project>
    <PropertyGroup>
        <Version>10.0.0-preview02</Version>
        <WarningsAsErrors>true</WarningsAsErrors>
        <UseWPF Condition="$(TargetFramework) == 'net10.0-windows'">true</UseWPF>
    </PropertyGroup>
    <ItemGroup Condition="$(AssemblyName) != 'System.Xaml' AND $(TargetFramework) != 'net10.0-windows'">
        <ProjectReference Include="$(MSBuildThisFileDirectory)System.Xaml\System.Xaml.csproj" PrivateAssets="All"/>
    </ItemGroup>
</Project>
